### ISSUE TITLE
Bot Refuses to Boot

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Lavender#62]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Ian\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Miku-Chan@1.1.1~prestart: Miku-Chan@1.1.1
6 info lifecycle Miku-Chan@1.1.1~start: Miku-Chan@1.1.1
7 verbose lifecycle Miku-Chan@1.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle Miku-Chan@1.1.1~start: PATH: C:\Users\Ian\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Git Projects\Miku-Chan\env\node_modules\.bin;C:\Users\Ian\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\local\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;C:\Users\Ian\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;D:\Program Files\Git\cmd;D:\Program Files\nodejs;D:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;D:\Program Files\PuTTY;C:\Program Files\Common Files\Autodesk Shared;D:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\GnuPG\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;D:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Ian\AppData\Local\Microsoft\WindowsApps;D:\Program Files\Microsoft VS Code\bin;C:\Users\Ian\AppData\Roaming\npm;D:\Program Files\heroku\bin;D:\Program Files\Git\usr\bin\vendor_perl;D:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle Miku-Chan@1.1.1~start: CWD: D:\Git Projects\Miku-Chan\env
10 silly lifecycle Miku-Chan@1.1.1~start: Args: [ '/d /s /c', 'node bot.js' ]
11 silly lifecycle Miku-Chan@1.1.1~start: Returned: code: 1  signal: null
12 info lifecycle Miku-Chan@1.1.1~start: Failed to exec start script
13 verbose stack Error: Miku-Chan@1.1.1 start: `node bot.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Ian\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Ian\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Miku-Chan@1.1.1
15 verbose cwd D:\Git Projects\Miku-Chan\env
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ian\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error Miku-Chan@1.1.1 start: `node bot.js`
22 error Exit status 1
23 error Failed at the Miku-Chan@1.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Not really much to go off of in terms of the logs.

**Comment by Incrested** [comment]
I've tried using `node bot.js`. It just flat crashes in terminal. Very odd in my book.

**Comment by Incrested** [comment]
So, I fixed the problem of the cryptos. But messages don't send and insta-crash the bot. Looking into further and temporarily closing #51

**Comment by Ultra03** [comment]
Any updates on this?

**Comment by Incrested** [comment]
Nothing as of this time: currently trying to find a GD for the logo so I can officially re-start the bot. But, internal test bot won't post properly

**Comment by Incrested** [comment]
Here's the update you wanted @Ultra03. Mind you: the ping command quite literally killed the bot: https://youtu.be/acbbTUdAbms

**Comment by Ultra03** [comment]
The bot boots, so closing this issue. The ping command works, however running the play command with a link crashes the bot. Opening another issue.
