### ISSUE TITLE
+kick Crashes Bot

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Lavender#70]
On line 6 of 'kick.js', the moderator role does not exist on the testing server. This needs to be customized within the web console and/or only allowed if the member has that permission: not that role. The bot crashes due to the following error:

```
D:\Git Projects\Lavender\commands\kick.js:7
    if (!message.member.roles.has(modRole.id)) {
                                         ^

TypeError: Cannot read property 'id' of null
    at Object.run (D:\Git Projects\Lavender\commands\kick.js:7:42)
    at Client.client.on.message (D:\Git Projects\Lavender\bot.js:44:30)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (D:\Git Projects\Lavender\node_modules\discor                                 d.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\Git Projects\Lavender\node_modules\disc                                 ord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (D:\Git Projects\Lavender\node_modules\disco                                 rd.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (D:\Git Projects\Lavender\node_modules\disc                                 ord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (D:\Git Projects\Lavender\node_modules\ws\lib\event-t                                 arget.js:120:16)
    at emitOne (events.js:115:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lavender@1.2.0 start: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lavender@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                 ging output above.
```

**Comment by Incrested** [comment]
Fixed Permissions and Breaking in 8a189d3e1d662aa58845fb386fb1c8a28d9db7c7. Issue arised when an admin tried to kick a member: could just be test interface.
