### ISSUE TITLE
Reload Command Doesn't Exist?

### ISSUE THREAD

**Issue by doamatto** [KnoxDevTeam/Lavender#92]
When running `+reload` without a command responds with the bot simply crashing (not wrong, but not right; should have warning on Discord). The main issue is that in the console it logs:
```
Error: Cannot find module './undefined.js'
2019-02-18T05:59:22.096997+00:00 app[worker.1]:     at Function.Module._resolveFilename (module.js:547:15)
2019-02-18T05:59:22.096999+00:00 app[worker.1]:     at Function.resolve (internal/module.js:18:19)
2019-02-18T05:59:22.097000+00:00 app[worker.1]:     at Object.run (/app/commands/reload.js:9:34)
2019-02-18T05:59:22.097002+00:00 app[worker.1]:     at Client.client.on.message (/app/bot.js:44:37)
2019-02-18T05:59:22.097004+00:00 app[worker.1]:     at emitOne (events.js:116:13)
2019-02-18T05:59:22.097005+00:00 app[worker.1]:     at Client.emit (events.js:211:7)
2019-02-18T05:59:22.097007+00:00 app[worker.1]:     at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2019-02-18T05:59:22.097009+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
2019-02-18T05:59:22.097011+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2019-02-18T05:59:22.097013+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2019-02-18T05:59:22.264102+00:00 heroku[worker.1]: State changed from up to crashed
```
I hope the issue is obvious in the sense of `undefined.js` not being `reload.js`

**Comment by doamatto** [comment]
Fixing it right now

**Comment by doamatto** [comment]
Added in 28e7551157fe84ce7828adcf21ee713cfc74c8a5
