### ISSUE TITLE
Node Security Error from Codacy

### ISSUE THREAD

**Issue by doamatto** [KnoxDevTeam/Lavender#96]
Just did a test on Codacy with a lot of work finished and in the logs it mentioned the following security error log: 
```
Docker exited with code 1
stdout: 
stderr: WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Error: npm-shrinkwrap.json is required for offline mode
    at module.exports (/app/lib/check.js:129:23)
    at Object.onCommand [as command] (/app/lib/commands/check.js:22:3)
    at doCb (/app/node_modules/subcommand/index.js:39:19)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Part of me thinks it could just be the way we have our Docker env setup in the config file, but let's swiftly ensure this gets fixed.

**Comment by doamatto** [comment]
This isn't unique to the `develop` branch: according to Codacy, it is also found on the `master` branch.

**Comment by doamatto** [comment]
Just sent an email to the Codacy team: looks like everything is fine on our end according to @Ultra03.
